---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - civoclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - civoclusters/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - civoclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - my.domain
  resources:
  - civomachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - civomachines/finalizers
  verbs:
  - update
- apiGroups:
  - my.domain
  resources:
  - civomachines/status
  verbs:
  - get
  - patch
  - update
