on:
  push:
    branches:
      - main
      
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  create-tag:
    runs-on: ubuntu-24.04
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tagger
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: 'none'
          INITIAL_VERSION: 0.0.0
  create-release:
    runs-on: ubuntu-24.04
    needs: [create-tag]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          make docker-build
          make docker-push

      - name: List contents of workspace (debug)
        run: ls -la $GITHUB_WORKSPACE

      - name: Create Release Artifacts
        run: make release
        env:
          RELEASE_TAG: ${{ github.ref_name }}

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./out/*
          tag_name: ${{ needs.create-tag.outputs.new_tag }}
          
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
